"""Ledger management for the ai-tracedoc plugin (core layer, agent-agnostic).

Naming rules, state file, project-level lock and volume management follow
the design doc §2/§4.3. The adapter (hooks/record-session.py) calls these
functions while holding the project lock. Ledger CONTENT is recorded
verbatim in whatever language the conversation used.
"""
import contextlib
import datetime
import fcntl
import glob
import json
import os
import re

LEDGER_SUFFIX = "tracedoc.md"
VOLUME_THRESHOLD_BYTES = 200 * 1024
STATE_FILENAME = ".tracedoc-state.json"
LOCK_FILENAME = ".tracedoc.lock"
MARKER_FILENAME = ".tracedoc-on"


class LedgerError(Exception):
    """Raised when the ledger cannot be located safely (e.g. ambiguous
    volumes). Callers should log and exit silently."""


def _today():
    return datetime.date.today().strftime("%Y%m%d")


def volume_number(filename):
    """Map a ledger filename to its volume number. No -NN suffix means
    volume 1."""
    match = re.search(r"-(\d+)\.md$", filename)
    if match:
        return int(match.group(1))
    return 1


def volume_filename(project, today, number):
    """Map a volume number to a filename. Volume 1 carries no number."""
    stem = LEDGER_SUFFIX[:-3]   # strip ".md" -> "tracedoc"
    if number == 1:
        return "%s-%s-%s" % (today, project, LEDGER_SUFFIX)
    return "%s-%s-%s-%02d.md" % (today, project, stem, number)


def ledger_pattern(project):
    return "*-%s-tracedoc*.md" % project


def create_volume(cwd, project, today, prev_fn, number):
    """Create a ledger volume with its header. Returns the filename."""
    name = volume_filename(project, today, number)
    path = os.path.join(cwd, name)
    if number == 1:
        header = "# %s · TraceDoc\n\n" % project
        header += ("This file is auto-generated by the ai-tracedoc plugin "
                   "from Claude Code session transcripts. "
                   "It has not been manually curated.\n\n")
    else:
        header = "# %s · TraceDoc (Volume %d)\n\n" % (project, number)
        header += "Continued from: [%s](./%s)\n\n" % (prev_fn, prev_fn)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(header)
    return name


def locate_latest_volume(cwd, project, state):
    """Locate the volume new sessions should append to.

    Prefers the state file's current_volume pointer; otherwise globs for
    the highest volume number. Raises LedgerError when multiple files
    share the highest number.
    """
    current = (state or {}).get("current_volume")
    if current and os.path.isfile(os.path.join(cwd, current)):
        return current
    matches = glob.glob(os.path.join(cwd, ledger_pattern(project)))
    if not matches:
        return None
    names = [os.path.basename(m) for m in matches]
    names.sort(key=volume_number)
    best = names[-1]
    if sum(1 for n in names if volume_number(n) == volume_number(best)) > 1:
        raise LedgerError("ambiguous ledger volumes: %s" % ", ".join(sorted(names)))
    return best


def format_session_header(date_str, title, session_id):
    return "\n## %s · %s\n\n<!-- session: %s -->\n\n" % (date_str, title, session_id)


def format_entries(entries):
    """Render Q&A entries as Markdown. Entries without an answer (a is
    None) get a question line only; a non-empty t prefixes the question
    with its local time."""
    parts = []
    for entry in entries:
        if entry.get("t"):
            parts.append("**Question:** %s · %s\n" % (entry["t"], entry["q"]))
        else:
            parts.append("**Question:** %s\n" % entry["q"])
        if entry.get("a"):
            parts.append("\n**Answer:** %s\n" % entry["a"])
        parts.append("")
    return "\n".join(parts)


def load_state(cwd):
    """Load the state file; a missing or corrupt file yields an empty dict."""
    path = os.path.join(cwd, STATE_FILENAME)
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        if isinstance(data, dict):
            return data
    except (IOError, ValueError):
        pass
    return {}


def save_state(cwd, state):
    """Atomically write the state file (temp file + rename)."""
    path = os.path.join(cwd, STATE_FILENAME)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(state, fh, ensure_ascii=False, indent=2)
    os.replace(tmp, path)


@contextlib.contextmanager
def project_lock(cwd):
    """Project-level exclusive lock covering the whole critical section:
    read state -> append ledger -> save state.

    Uses fcntl.flock on POSIX (Linux/macOS); Windows is not supported
    (see design doc §8). Callers must hold the lock before load_state /
    append_session / save_state.
    """
    path = os.path.join(cwd, LOCK_FILENAME)
    with open(path, "a") as lock_fh:
        fcntl.flock(lock_fh.fileno(), fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(lock_fh.fileno(), fcntl.LOCK_UN)


def _append_text(volume_path, text):
    """Plain append (single write). Caller must hold the project lock."""
    with open(volume_path, "a", encoding="utf-8") as fh:
        fh.write(text)


def append_footer_link(cwd, prev_fn, next_fn):
    """Append the "Continued in" footer to the old volume. Caller must
    hold the project lock."""
    _append_text(os.path.join(cwd, prev_fn),
                 "\n\n---\n\nContinued in: [%s](./%s)\n" % (next_fn, next_fn))


def should_start_new_volume(volume_path, session_is_new, threshold):
    """Only a NEW session may start a new volume, and only when the
    current one exceeds the threshold; continuations never split."""
    if not session_is_new:
        return False
    try:
        size = os.path.getsize(volume_path)
    except OSError:
        return False
    return size > threshold


def append_session(cwd, project, session, state, today=None,
                   threshold=VOLUME_THRESHOLD_BYTES):
    """Append one session's Q&A to the ledger (volume orchestration,
    design doc §4.3 step 4).

    session: {"session_id","title","date","entries":[{"q","a","t"}]}
    Caller must hold project_lock(cwd) — the lock spans read-state →
    write-ledger → write-state. Updates and returns state in place;
    callers should not pass sessions with empty entries.
    """
    sid = session["session_id"]
    known = (state.get("sessions") or {}).get(sid)
    if known and known.get("volume"):
        _append_text(os.path.join(cwd, known["volume"]),
                     format_entries(session["entries"]))
        return state

    current = locate_latest_volume(cwd, project, state)
    if current is not None:
        if should_start_new_volume(os.path.join(cwd, current), True, threshold):
            number = volume_number(current) + 1
            new_fn = create_volume(cwd, project, today or _today(),
                                   current, number)
            append_footer_link(cwd, current, new_fn)
            current = new_fn
    else:
        current = create_volume(cwd, project, today or _today(), None, 1)

    text = format_session_header(session["date"], session["title"], sid)
    text += format_entries(session["entries"])
    _append_text(os.path.join(cwd, current), text)

    state.setdefault("sessions", {})[sid] = {"offset": 0, "volume": current}
    state["current_volume"] = current
    return state
